# Generated by Django 5.0 on 2023-12-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("devices.capabilities.on_off", "on_off"),
                            ("devices.capabilities.color_setting", "color_setting"),
                            ("devices.capabilities.mode", "mode"),
                            ("devices.capabilities.range", "range"),
                            ("devices.capabilities.toggle", "toggle"),
                        ],
                        max_length=128,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "retrievable",
                    models.BooleanField(verbose_name="Доступность запроса состояния"),
                ),
                (
                    "reportable",
                    models.BooleanField(verbose_name="Признак включенного оповещения"),
                ),
                ("parameters", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "Умение",
                "verbose_name_plural": "Умения",
            },
        ),
        migrations.CreateModel(
            name="BaseProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("devices.properties.float", "float"),
                            ("devices.properties.event", "event"),
                        ],
                        max_length=128,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "retrievable",
                    models.BooleanField(verbose_name="Доступность запроса состояния"),
                ),
                (
                    "reportable",
                    models.BooleanField(verbose_name="Признак включенного оповещения"),
                ),
                ("parameters", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "Свойство",
                "verbose_name_plural": "Свойства",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Имя")),
                ("description", models.TextField(verbose_name="Описание")),
                ("type", models.TextField(verbose_name="Тип устройства")),
                ("room", models.TextField(verbose_name="Комната")),
                ("custom_data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
            },
        ),
        migrations.CreateModel(
            name="DeviceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.TextField()),
                ("model", models.TextField()),
                ("hw_version", models.TextField()),
                ("sw_version", models.TextField()),
            ],
            options={
                "verbose_name": "Информация об устройстве",
                "verbose_name_plural": "Информация об устройствах",
            },
        ),
        migrations.CreateModel(
            name="DeviceCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="Показатель")),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.basecapability",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение конкретного устройства",
                "verbose_name_plural": "Умения конкретного устройства",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="device_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="devices.deviceinfo",
            ),
        ),
        migrations.CreateModel(
            name="DeviceProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="Показатель")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="devices.device",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.baseproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свойство конкретного устройства",
                "verbose_name_plural": "Свойства конкретного устройства",
            },
        ),
    ]
